namespace VRCFaceTracking.Babble;
public partial class BabbleOSC
{
    public Dictionary<string, float> BabbleExpressionMap = new()
    {
        { "/cheekPuffLeft", 0f },
        { "/cheekPuffRight", 0f },
        { "/cheekSuckLeft", 0f },
        { "/cheekSuckRight", 0f },
        { "/jawOpen", 0f },
        { "/jawForward", 0f },
        { "/jawLeft", 0f },
        { "/jawRight", 0f },
        { "/noseSneerLeft", 0f },
        { "/noseSnerrRight", 0f },
        { "/mouthFunnel", 0f },
        { "/mouthPucker", 0f },
        { "/mouthLeft", 0f },
        { "/mouthRight", 0f },
        { "/mouthRollUpper", 0f },
        { "/mouthRollLower", 0f },
        { "/mouthShrugUpper", 0f },
        { "/mouthShrugLower", 0f },
        { "/mouthClose", 0f },
        { "/mouthSmileLeft", 0f },
        { "/mouthSmileRight", 0f },
        { "/mouthFrownLeft", 0f },
        { "/mouthFrownRight", 0f },
        { "/mouthDimpleLeft", 0f },
        { "/mouthDimpleRight", 0f },
        { "/mouthUpperUpLeft", 0f },
        { "/mouthUpperUpRight", 0f },
        { "/mouthLowerDownLeft", 0f },
        { "/mouthLowerDownRight", 0f },
        { "/mouthPressLeft", 0f },
        { "/mouthPressRight", 0f },
        { "/mouthStretchLeft", 0f },
        { "/mouthStretchRight", 0f },
        { "/tongueOut", 0f },
        { "/tongueUp", 0f },
        { "/tongueDown", 0f },
        { "/tongueLeft", 0f },
        { "/tongueRight", 0f },
        { "/tongueRoll", 0f },
        { "/tongueBendDown", 0f },
        { "/tongueCurlUp", 0f },
        { "/tongueSquish", 0f },
        { "/tongueFlat", 0f },
        { "/tongueTwistLeft", 0f },
        { "/tognueTwistRight", 0f }
    };
}
